### ISSUE TITLE
Embed a link to the Solid React SDK in footer on demo sites

### ISSUE THREAD

**Issue by megoth** [Inrupt-inc/generator-solid-react#80]
I think https://generator.inrupt.com/ and https://dev-generator.inrupt.com/ should point to the [Solid React SDK](https://github.com/inrupt-inc/solid-react-sdk), for those curious people stumbling upon them. Also a little bit of context is nice for those that just stumble upon them, or are given URLs from others.

**Comment by james-martin-jd** [comment]
This was resolved in version 0.4.0 of the generator. There is now a footer with some helpful links at the bottom right.
